services:
  tealeave-rest:
    container_name: tealeave-rest
    image: ghcr.io/coocobolo/thesis/tealeave-rest:latest
    build:
      dockerfile: builds/Dockerfile
      tags:
        - ghcr.io/coocobolo/thesis/tealeave-rest:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - tealeave-rest-data:/app
volumes:
  tealeave-rest-data:
